import Bonanza from "../../assets/images/bonanaza.png";
import Breakout from "../../assets/images/breakout.png";
import Diners from "../../assets/images/diners.png";
import Edenrobe from "../../assets/images/ednrobe.png";
import Engine from "../../assets/images/engine.png";
// import Furor from "../../assets/images/furor.png";
import Gulahmed from "../../assets/images/gulahmed.png";
import Outfitters from "../../assets/images/outfitters.png";

export const appData = [
  {
    color: [],
    pictures: [Bonanza],
    size: ["4-5", "6-7", "8-9", "10-11", "11-12"],
    tag: [],
    _id: "5eec72fdc0c4d53968767d16",
    id: 37356,
    name: "Blue-Denim-Kurti",
    colors: ["blue"],
    price: 2980,
    discount: 0,
    salePrice: 2980,
    description: "",
    tags: ["kids", "1 Piece"],
    rating: 3,
    category: "kids",
    buyUrl: "https://www.bonanzasatrangi.com/pk/ks1p-051-blue-blue-denim-kurti",
    gender: "kids",
    brand: "1 Piece",
    date: "2020-06-19T13:10:20.566Z",
    mainBrand: "bonanza",
  },
  {
    color: [],
    pictures: [Breakout],
    size: ["1-2y", "2-3y", "3-4y", "4-5y", "5-6y"],
    tag: [],
    _id: "5eed266ac0c4d54e10a99b92",
    id: 2427,
    name: "BOYS PINSTRIPE COLLAR SHIRT",
    stock: 0,
    price: 909,
    discount: 0,
    salePrice: 0,
    description: "",
    tags: ["kids", "NEW IN"],
    rating: 3,
    category: "kids",
    colors: [],
    buyUrl:
      "https://www.breakout.com.pk/collections/new-in-3/products/k20sw375-red",
    gender: "kids",
    brand: "NEW IN",
    date: "2020-06-20T01:56:10.514Z",
    mainBrand: "breakout",
  },
  {
    color: [],
    pictures: [Diners],
    size: [
      "12 (2-3 year)",
      "14 (3-4 year)",
      "16 (4-5 year)",
      "18 (5-6 year)",
      "+ 6",
      "+ -3",
    ],
    tag: [],
    _id: "5eec8352c0c4d54a14da1c99",
    id: 41937,
    name: "Boys Kurta In yellow KBKS-0050 Yellow",
    price: 2,
    discount: 0,
    salePrice: 0,
    description: "",
    tags: ["kids", "Mix"],
    category: "kids",
    colors: [],
    buyUrl:
      "https://diners.com.pk//collections/boys/products/boys-kurta-in-blue-kbks-0050",
    gender: "kids",
    brand: "Mix",
    date: "2020-06-19T14:20:18.514Z",
    mainBrand: "diners",
  },
  {
    color: [],
    pictures: [Edenrobe],
    size: ["02-3y", "05y", "07-8y", "09-10y"],
    tag: [],
    _id: "5eecd80fc0c4d535ac0361a6",
    id: 29385,
    name: "EBTT20-010-Blue Multi",
    price: 545,
    discount: 0,
    salePrice: 0,
    description: "",
    tags: ["kids", "Tank Top"],
    rating: 3,
    category: "kids",
    colors: ["blue multi"],
    buyUrl: "https://edenrobe.com/product/kids/boys/ebtt20-010-blue-multi/",
    gender: "kids",
    brand: "Tank Top",
    date: "2020-06-19T20:21:45.904Z",
    mainBrand: "edenrobe",
  },
  {
    color: [],
    pictures: [Engine],
    size: ["l", "m", "s", "xs"],
    tag: [],
    _id: "5eecde3dc0c4d512984f3934",
    id: 21418,
    name: "0LO022",
    price: 1,
    discount: 0,
    salePrice: 0,
    description: "",
    tags: ["women", "Woven Tops"],
    category: "women",
    colors: ["off white"],
    buyUrl: "https://www.engine.com.pk/collections/woven-top/products/0lo022-3",
    gender: "women",
    brand: "Woven Tops",
    date: "2020-06-19T20:48:08.627Z",
    mainBrand: "engine",
  },
  {
    color: [],
    pictures: [Gulahmed],
    size: [],
    tag: [],
    _id: "5eece5a0c0c4d54e14428bcc",
    id: 62713,
    name: "White Twil Formal Shirt CM-YD-2765 BG",
    price: 2000,
    discount: 0,
    salePrice: 2000,
    description: "",
    tags: ["men", "DRESS SHIRTS"],
    rating: 4,
    category: "men",
    colors: ["white"],
    buyUrl:
      "https://www.gulahmedshop.com/white-twil-formal-shirt-cm-yd-2765-bg",
    gender: "men",
    brand: "DRESS SHIRTS",
    date: "2020-06-19T21:19:35.339Z",
    mainBrand: "gulahmed",
  },
  {
    color: [],
    pictures: [Outfitters],
    size: ["xs", "s", "l"],
    tag: [],
    _id: "5eed0d93c0c4d545a49ce683",
    id: 99506,
    name: "Ruffled Sleeves Shirt",
    price: 2290,
    discount: 0,
    salePrice: 0,
    description: "",
    tags: ["women", "Shirts"],
    rating: 4,
    category: "women",
    colors: ["blk"],
    buyUrl:
      "https://outfitters.com.pk/collections/women-shirts/products/wtf102038blk",
    gender: "women",
    brand: "Shirts",
    date: "2020-06-20T00:10:06.763Z",
    mainBrand: "outfitters",
  },
];
