export const GET_PRODUCT_LIST_REQUEST = "GET_PRODUCT_LIST_REQUEST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAILURE = "GET_PRODUCT_LIST_FAILURE";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const SUBTRACT_PRODUCT = "SUBTRACT_PRODUCT";

export const GET_BRAND_PRODUCT_LIST_REQUEST = "GET_BRAND_PRODUCT_LIST_REQUEST";
export const GET_BRAND_PRODUCT_LIST_SUCCESS = "GET_BRAND_PRODUCT_LIST_SUCCESS";
export const GET_BRAND_PRODUCT_LIST_FAILURE = "GET_BRAND_PRODUCT_LIST_FAILURE";

export const GET_SELECTED_BRAND_PRODUCT_LIST_REQUEST =
  "GET_SELECTED_BRAND_PRODUCT_LIST_REQUEST";
export const GET_SELECTED_BRAND_PRODUCT_LIST_SUCCESS =
  "GET_SELECTED_BRAND_PRODUCT_LIST_SUCCESS";
export const GET_SELECTED_BRAND_PRODUCT_LIST_FAILURE =
  "GET_SELECTED_BRAND_PRODUCT_LIST_FAILURE";

export const REGISTER_REQUEST = "USERS_REGISTER_REQUEST";
export const REGISTER_SUCCESS = "USERS_REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USERS_REGISTER_FAILURE";

export const LOGIN_REQUEST = "USERS_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USERS_LOGIN_FAILURE";
export const LOGIN_RESET = "LOGIN_RESET";
export const LOGOUT = "USERS_LOGOUT";

export const GETALL_REQUEST = "USERS_GETALL_REQUEST";
export const GETALL_SUCCESS = "USERS_GETALL_SUCCESS";
export const GETALL_FAILURE = "USERS_GETALL_FAILURE";

export const DELETE_REQUEST = "USERS_DELETE_REQUEST";
export const DELETE_SUCCESS = "USERS_DELETE_SUCCESS";
export const DELETE_FAILURE = "USERS_DELETE_FAILURE";


export const USER_REQUEST_LOUOUT = "USER_REQUEST_LOUOUT";
export const USER_SUCESS_LOUOUT = "USER_SUCESS_LOUOUT";
export const USER_FAILURE_LOUOUT = "USER_FAILURE_LOUOUT";

export const SUCCESS = "ALERT_SUCCESS";
export const ERROR = "ALERT_ERROR";
export const CLEAR = "ALERT_CLEAR";


export const REGISTER_RESET = "REGISTER_RESET"
export const LOCAL_STRAGE_CHANGE = "LOCAL_STRAGE_CHANGE";